repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.104.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_lookup'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_empty_list_equality'
          - '--args=--only=terraform_json_syntax'
          - '--args=--only=terraform_map_duplicate_keys'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_module_shallow_clone'
          - '--args=--only=terraform_module_version'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_unused_required_providers'
          - '--args=--only=terraform_workspace_remote'
      - id: terraform_validate
      - id: terraform_trivy
        args:
          - --args=--skip-dirs="**/.terraform"
