name: Terraform
on: [push]
jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: terraform fmt -check -recursive -diff

  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: examples/test
      - name: Terraform Validate
        run: terraform validate
        working-directory: examples/test

  mock-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: examples/test
      - name: Terraform Plan (Mock)
        run: terraform plan
        working-directory: examples/test

  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: examples/test
